### ISSUE TITLE
User Interface Design in Streamlit

### ISSUE THREAD

**Issue by sumanths012** [sumanths012/SymptoSense#12]
**Title:** Optimizing Layout & User Experience for Health Metrics Input

**Description:** Design the user interface for the Streamlit app, focusing on layout, user experience, and ease of input for health metrics.

https://github.com/sumanths012/SymptoSense/blob/f958b2ad9aa9ced6ea23617a1f7a3116d80d1b1d/streamlit_web_app.py#L8

![Image](https://github.com/user-attachments/assets/5c490846-8f3f-46c3-ab74-3ecbc3580acd)

**Comment by jahnavip77** [comment]
![Image](https://github.com/user-attachments/assets/85ecfa63-9540-426c-8cf9-1b077621cf2d)
