### ISSUE TITLE
Implement OCR for Text Extraction

### ISSUE THREAD

**Issue by sumanths012** [sumanths012/SymptoSense#29]
**Title:** Implement Optical Character Recognition (OCR) for Image Text Extraction

**Description:**
Integrate Tesseract OCR for extracting medical test values (Glucose, Insulin) from uploaded and captured images.
Establish parsing logic to identify specific medical terms in the extracted text.

**Tasks:**
Implement process_image and parse_text functions.
Developed logic to extract values based on predefined field names.

https://github.com/sumanths012/SymptoSense/blob/532b7a3712297653bf4bc8b125e5d76cf1a8a53a/streamlit_web_app.py#L19

**Comment by Prathapng** [comment]
![OCR_text_extraction](https://github.com/user-attachments/assets/3189702f-0f11-4be0-86cc-e64c99bf9923)
