### ISSUE TITLE
Website Frontend Design with Streamlit

### ISSUE THREAD

**Issue by sumanths012** [sumanths012/SymptoSense#7]
Task: Create the frontend design using Streamlit for the diabetes prediction web app.

Description: Design the simple web interface using Streamlit, allowing users to input medical data for diabetes prediction and view results interactively.![Image](https://github.com/user-attachments/assets/517ba4bd-58e8-4856-a730-492ee571f8fa)

Due Date: 09/25/24

https://github.com/sumanths012/SymptoSense/blob/ad4bada5bfc0b89588cbec53560bf43850ffa3ed/streamlit_web_app.py#L1

**Comment by jahnavip77** [comment]
![Image](https://github.com/user-attachments/assets/e0467bfb-0752-4e14-9ba5-5bcf8ce7667a)
